packages:
  - name: app
    type: go
    srcs:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
    deps:
      - components/common-go:lib
      - components/public-api/go:lib
    env:
      - CGO_ENABLED=0
    config:
      packaging: app
      dontTest: true
